config/routes.rb
Rails.application.routes.draw do
  get 'users/view'

  devise_for :users
  resources :searches
  resources :poems do
  	resources :comments
  	member do
    	put "like", to: "poems#upvote"
   	 	put "dislike", to: "poems#downvote"
 	end
  end



  resources :users, only: [:show]
  root "poems#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :poems
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :poem
	
	validates :body, presence: true, length: { minimum: 10}
end

app/models/poem.rb
class Poem < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_many :comments,dependent: :destroy
	acts_as_votable
	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true, length: { minimum: 50 }
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :category

  def search_poems
  	poems = Poem.all
 	poems = poems.where('title LIKE ?',tittle) if tittle.present?	
 	poems = poems.where('body LIKE ?',body) if body.present?
 	poems = poems.where('category_id == ?',category) if category.present?
  	return poems
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :comments,dependent: :destroy
  has_many :poems,dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:first_name,:last_name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @poem = Poem.find(params[:poem_id])
    @comment = @poem.comments.create(comment_params)
    @comment.user = current_user
    if @comment.save
    	redirect_to poem_path(@poem),notice:"Successfully added comment"
    else
    	redirect_to poem_path(@poem),alert:"Cant add comment"
    end
  end
 
  def destroy
    @poem = Poem.find(params[:poem_id])
    @comment = @poem.comments.find(params[:id])
    @comment.destroy
    redirect_to poem_path(@poem)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
	before_action :find_poem, only:[:show,:edit,:update,:destroy]
	before_action :authenticate_user!, except:[:index,:show]
	def index
		if params[:category].blank?	
			@poems = Poem.all
		
		else
			@category_id = Category.find_by(name: params[:category]).id
			@poems = Poem.where(category_id: @category_id) 
		end
		if params[:search]
			@poems = Poem.where('title LIKE ?', "%#{params[:search]}%")
		end
	end

	def show
		@poems = Poem.new
	end

	def edit	
	end

	def update
		if @poem.update(poem_params)
			redirect_to poem_path(@poem)
		else
			render 'edit'
		end
	end

	def new
		@poem = current_user.poems.build
	end

	def create
		@poem = current_user.poems.build(poem_params)
		
		if @poem.save
			redirect_to root_path
		else
			render 'new'
		end	
	end

	def destroy
		@poem.destroy
		redirect_to root_path
	end
	def upvote 
  		@poem = Poem.find(params[:id])
  		@poem.upvote_by current_user
  		redirect_back fallback_location: poem_path(@poem)
	end  

	def downvote
  		@poem = Poem.find(params[:id])
  		@poem.downvote_by current_user
  		redirect_back fallback_location: poem_path(@poem)
  		
	end



	private
		def poem_params
			params.require(:poem).permit(:title,:body,:category_id,:search)
			
		end

		def find_poem
			@poem = Poem.find(params[:id])	
		end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	def new
		@search = Search.new
		#@category = Poem.uniq.pluck(:category)
	end

	def create
		@search = Search.create!(search_params)
		redirect_to @search
	end

	def show
		@search = Search.find(params[:id])
	end

	
	private

	def search_params
		params.require(:search).permit(:tittle,:body,:category_id)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Poetsociety</title>
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<style>
			.panel-body  {
				word-break:break-all
				}

		</style>
	</head>
	<body>
		<nav class="navbar navbar-default">
			<div class="container-fluid">

				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="<%= root_path %>">PoemSociety</a>
				</div>

				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<%if user_signed_in?%>
						<li><%=link_to "Add Poem", new_poem_path %></li>
						<%end%>
						<li><%= link_to "Advanced Search", new_search_path %></li>

					</ul>
					<form class="navbar-form navbar-left">
						<%= form_tag(poems_path, method: :get) do %>
						<%= text_field_tag :search %>
						<%= submit_tag 'Search' %>
						<% end %>
					</form>



					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
							<ul class="dropdown-menu">
								<% Category.all.each do |cat| %>
								<li><%= link_to cat.name, poems_path(category: cat.name) %></li>
								<% end %>
								<li><%= link_to "All", poems_path %></li>
							</ul>
							<li>
								<%if user_signed_in?%>
								<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name+" "+current_user.last_name%> <span class="caret"></span></a>
									<ul class="dropdown-menu">
										<li><%= link_to "Update Account", edit_user_registration_path %>
										</li>
										<li><%= link_to "View Poems", user_path(current_user) %>
										</li>
										<li><%= link_to "Sign Out", destroy_user_session_path,method: :delete%></li>
									</li>
								</ul>
							</li>


							<%else%>
							<li><%= link_to "Sign Up", new_user_registration_path%></li>
							<li><%= link_to "Sign in", new_user_session_path%></li>

							<%end%>


						</ul>
					</div>
				</div>
			</nav>
			<div class="container">
				<%if notice%>
				<div class="alert alert-success"><p class="notice"><%= notice %></p></div>
				<%elsif alert%>
				<div class="alert alert-danger"><p class="notice"><%= alert %></p></div>
				<%end%>
			</div>

			<%= yield %>
		</body>
	</html>

app/views/poems/_form.html.erb
<%= simple_form_for @poem do |f|%>

	<%= f.input :title,label: "Poem Title"%>
	<%= f.input :body,label: "Body"%>
	<%= f.select :category_id, Category.all.collect {|c| [ c.name, c.id ] },label: "Category" %>
	<br>
	<%= f.button :submit%>
<% end %>

app/views/poems/edit.html.erb
<div class="container">
	<h2>Edit Poem</h2>
	<%= render 'form' %>
</div>

app/views/poems/index.html.erb
<div class="container">
	<h2>Welcome to index</h2>
	
	<div class="container">
		<div class="row">
				
				<% @poems.each do |poem| %>
				<h3> <%= link_to poem.title, poem_path(poem)%> <small>created by <strong><%= poem.user.first_name%></strong> <%= time_ago_in_words(poem.created_at) %> ago</small></h3>
				<hr/>				

				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/poems/new.html.erb
<div class="container">
	<h1>Add New Poem</h1>
	<%= render 'form' %>
</div>

app/views/poems/show.html.erb
<div class="container">
	<h2><%= @poem.title %></h2>
	<%= @poem.user.first_name%>
	<div class="well"><%= simple_format(@poem.body)%></div>
	
	
	<%= link_to like_poem_path(@poem), method: :put do %>
	<span class="glyphicon glyphicon-thumbs-up"></span>
	<%= @poem.get_upvotes.size %>
	<%= link_to dislike_poem_path(@poem), method: :put do %>
	<span class="glyphicon glyphicon-thumbs-down"></span>
	<%= @poem.get_downvotes.size %>
	<% end %>
	<% end %>
	<h2>Comments</h2>
	<%= simple_form_for([@poem, @poems.comments.build]) do |f| %>
	<%= f.input :body,label: "Comment"%>
	<%= f.button :submit%>
	<% end %>
	<br>
	<div class="row">
	<% @poem.comments.order("created_at DESC").each do |comment| %>
		<div class="col-sm-8">
			<div class="panel panel-default">
				<div class="panel-heading">
					<div class="row">
						<div class="col-md-6"><strong><%= comment.user.first_name%></h4></strong> <span class="text-muted">commented <%= time_ago_in_words(comment.created_at)%> ago</div>
						<div class="col-md-6"></div>
					</div>
					

		
					
				</div>
				<div class="panel-body">
					<%= comment.body %>
				</div>
			</div>
		</div>
	<% end %>
	</div>
			<% if user_signed_in? %>
				<% if @poem.user_id == current_user.id %>
				<%= link_to "Edit", edit_poem_path(@poem)%>
				<%= link_to "Delete", poem_path(@poem), method: :delete,data:{confirm: 'Are you sure?'}%>
				<%end%>
			<%end%>
			
		</div>

app/views/searches/new.html.erb
<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-4">
		<%= simple_form_for @search do |f| %>
		<%= f.input :tittle, label: "title" %>
		<%= f.input :body, label: "body" %>
		<%= f.select :category_id, Category.all.collect {|c| [ c.name, c.id ] },label: "Category" %>
		<br>
		<%= f.button :submit%>
		<% end %>
	</div>
	<div class="col-md-4"></div>
</div>

app/views/searches/show.html.erb
<% if @search.search_poems.empty? %>
	No results
<%else %>
 <%= @search.search_poems.count %> Results
 <% @search.search_poems.each  do |poem| %>
				<h3> <%= link_to poem.title, poem_path(poem)%> <small>created by <strong><%= poem.user.first_name%></strong> <%= time_ago_in_words(poem.created_at) %> ago</small></h3>
				<hr/>				

<% end %>
<% end %>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<div class="panel panel-default">
					<div class="panel-heading">Name</div>
					<div class="panel-body">
						<%= @user.id%> <%= @user.first_name%> <%= @user.last_name%> 
					</div>
					<div class="panel-heading">Email</div>
					<div class="panel-body">
						<%= @user.email%>
					</div>
			</div>
		</div>
		<div class="col-md-8">
			<%@user.poems.each do |poem|%>
				<div class="panel panel-default">
					<div class="panel-heading"><h3><%= poem.title%></h3></div>
					<div class="panel-body">
						<%= raw poem.body%><br>
						<button class="btn btn-primary" type="button">
  							Comments <span class="badge"><%= poem.comments.count%></span>
						</button>
						<button class="btn btn-primary" type="button">
  							Likes <span class="badge"><%= poem.get_upvotes.size%></span>
						</button>
						<button class="btn btn-primary" type="button">
  							Dislikes<span class="badge"><%= poem.get_downvotes.size%></span>
						</button>
						
					</div>
				</div>
			<% end%>
		</div>
	</div>
	
</div>